name: Murder
version: '${version}'
main: com.pwdim.murder.Murder
description: §aMinigame Murder
depend:
  - SlimeWorldManager
commands:
  game:
    description: game
    permission: arcade.manage
  murder:
    description: play murder
    permission: ""
    aliases:
      - play
      - playmurder
      - murderjoin
